# Reminder for you:
# You must setup this config before using the A.P.V.E. Not configuring this config can lead to false punishments and message-blockings. Also, configure the punishment command syntax for your punishment plugin if you want avoid crashs!!!

# For russian administrators:
# Normalizer converts any cyrilic symbols into latin alphabet. Consequently, the addition of new banned words must be fully in latin alphabet like (шлюха --> shlyuha).
# Full normalization documentation you can see in documentation.txt

thresholds:
  high: 0.78  
  medium: 0.57  

# 1. Insult words
insult-words:
  # Russian (Translit)
  - "eblan"
  - "eblanische"
  - "eblanka"
  - "dolboeb"
  - "dolboyob"
  - "dolboebina"
  - "dolboyascher"
  - "ebanat"
  - "ebanashka"
  - "ebanatik"
  - "hueplet"
  - "huesos"
  - "huesosi"
  - "hueglot"
  - "hueputalo"
  - "huenosec"
  - "huevat"
  - "huedrysch"
  - "pizdabol"
  - "pizdabolka"
  - "pizdaliz"
  - "blyad"
  - "blyat"
  - "blyadb"
  - "blyatb"
  - "blyadina"
  - "blyadskiy"
  - "blyadstvo"
  - "blyadun"
  - "blyadota"
  - "gandon"
  - "ochkoshnik"
  - "gandonische"
  - "mudak"
  - "mudila"
  - "pidor"
  - "pidoras"
  - "pidrenok"
  - "pidrila"
  - "pidrische"
  - "pidorazina"
  - "mrazb"
  - "ueban"
  - "ebenb"
  - "mrazota"
  - "otrodbe"
  - "manda"
  - "vyblyadok"
  - "shlyuha"       
  - "shlyushka"   
  - "shalava"       
  - "shmara"        
  - "potaskuha"     
  - "potaskushka"  
  - "davalka"      
  - "podstilka"    
  - "prostitutka"     
  - "suchka"       
  - "tvarb"       
  - "paskuda"
  - "sirota"
  - "bezmamysh"
  - "vyblyadok" 
  - "ebut"
  - "ebatb"
  - "ebat"
  - "ebal"
  - "ebala"
  - "ebem"
  - "ebaniy"
  - "ebuchiy"
  - "zaebal"
  - "naebal"
  - "doebalsya"
  - "poebat"
  - "trahaem"
  - "trahnuli"
  - "trahnul"
  - "trahatsa"
  - "trahal"
  - "trahala"
  - "trakhat"
  - "vyebali"
  - "vyebal"
  # English
  - "fuck"
  - "shit"
  - "dick"
  - "cunt"
  - "hoe"
  - "fag"
  - "pussy"
  - "bastard"
  - "bitch"
  - "asshole"
  - "dickhead"
  - "retard"
  - "loser"
  - "dumbass"
  - "idiot"
  - "wanker"
  - "twat"
  - "dipshit"
  - "moron"
  - "prick"
  - "imbecile"
  - "scumbag"
  - "douchebag"

# 1.1. Family insult words
family-insult-words:
  # Russian (Translit)
  - "mam"
  - "pap"
  - "bat"
  - "otc"
  - "mamu"
  - "mame"
  - "mamul"
  - "matb"
  - "macheha"
  - "otca"
  - "batya"
  - "bate"
  - "opekun"
  - "opeka"
  - "rodnyu"
  - "roditeley"
  - "roditelyam"
  - "mamka"       
  - "mamasha"     
  - "mamochka"     
  - "matushka"     
  - "mamulya"      
  - "maman"   
  - "mama" 
  - "mamy"       
  - "papa"     
  - "papu"      
  - "pape"      
  - "otets"    
  - "otcu"    
  - "otcom"    
  - "babushka"    
  - "dedushka"
  - "doch"       
  - "dochka"   
  - "dochenka"   
  - "sestra"      
  - "sestru"    
  - "brata"       
  # English
  - "motherfucker"
  - "milf"
  - "mother"
  - "mom"
  - "mum"
  - "father"
  - "dad"
  - "parents"
  - "orphan"

family-roots:
  - "roditel"  
  - "opek"      
  - "mother"
  - "father"

bad-roots:
  # Russian (Translit)
  - "eblan"
  - "dolboeb"
  - "huesos"
  - "gandon"
  - "mudak"
  - "pidr"
  - "pidoras"
  - "mraz"
  - "ueban"
  - "vyblyad"
  - "shlyuh"        
  - "shalav"       
  - "prostitut"     
  - "potaskuh"  
  # English
  - "bastard"
  - "whore"
  - "slut"
  - "faggot"

expressive-words:
  # Russian (Translit)
  - "pizda"
  - "pizdec"
  - "blyadb"
  - "nahuy"
  - "pohuy"
  # English
  - "fuck"
  - "fucking"
  - "shit"
  - "crap"
  - "damn"

# 4. Ads and links
ad-words:
  - "funpay"
  - "playerok"
  - "aternos"
  - "minehut"
  - "reallyworld"
  - "dexland"
  - "funtime" 
  - "holyworld"
  - "funmine"
  - "teslacraft"
  - "vinemc" 
  - "bixland"
  - "mixland"  
  - "spookytime"
  - "ragemine"                          

# 5. Social networks and other
social:
  - "disgd"
  - "dsgg"
  - "tgme"
  - "vkcom"
  - "vkme"

allowed-words:
  - "zdarova"
  - "zdorov"
  - "zdorova"
  - "privet"
  - "zdrastvuyte"
  - "zastrahuyte"
  - "zastrahuy"
  - "strahovanie"
  - "upotreblyat"
  - "upotreblyatb"
  - "oskorblyat"
  - "oskorblyatb"
  - "potreblenie"
  - "soblyudat"
  - "kolebaniya"
  - "kolebat"
  - "kolebalsya"
  - "rubl"
  - "hleb"
  - "komanda"
  - "komandu"
  - "rebyata"
  - "rebenok"
  - "fact"
  - "who"
  - "whom"
  - "much"
  - "match"
  - "piece"
  - "peace"
  - "beach"
  - "block"
  - "pvp"
  - "pve"
  - "afk"
  - "spawn"
  - "home"
  - "tpa"
  - "hue"
  - "hues"
  - "retardant"
  - "retarder"
  - "dickens"
  - "sped"
  - "crystal"
  - "method"
  - "department"
  - "nutmeg"
  - "oatmeal"
  - "welcome"
  - "mebel"
  - "trebovat"
  - "nebo"
  - "serebro"
  - "nablyudat"
  - "sablya"
  - "opazdyvat"
  - "mudry"
  - "bermuda"
  - "pedal"
  - "torpedo"
  - "vikipedia"
  - "sukno"
  - "barsuk"
  - "shlyupa"
  - "moroz"
  - "mramor"
  - "london"
  - "matematika"
  - "format"
  - "avtomat"
  - "aromat"
  - "geroy"
  - "narkoz"
  - "metod"
  - "shirt"
  - "batch"
  - "pitch"
  - "ditch"
  - "witch"
  - "stich"
  - "duck"
  - "dock"
  - "deck"
  - "medic"
  - "predict"
  - "dictate"
  - "focus"
  - "factual"
  - "clas"
  - "glas"
  - "gras"
  - "pas"
  - "mas"
  - "asemble"
  - "asist"
  - "aset"
  - "asume"
  - "cucumber"
  - "document"
  - "acumulate"
  - "county"
  - "scunthorpe"
  - "wed"
  - "weding"
  - "sweden"
  - "shoe"
  - "scrap"
  - "scrape"
  - "chore"
  - "shore"
  - "popcorn"
  - "methane"
  - "mathematics"
  - "comand"
  - "aple"
  - "server"
  - "helo"
  - "suces"
  - "mesage"

adult-words:
  - "gashish"      
  - "anasha"         
  - "marihuyana"   
  - "marihuana"
  - "kosyak"        
  - "boshki"        
  - "geroin"        
  - "kokain"         
  - "kokos"         
  - "methamfetamin"  
  - "amfetamin"     
  - "ekstazi"       
  - "spays"            
  - "narkotik"       
  - "psylocybin"
  - "marki"                 
  - "weed"
  - "marijuana"
  - "cannabis"
  - "hashish"
  - "ganja"
  - "cocaine"
  - "heroin"
  - "methamphetamine"
  - "amphetamine"
  - "ecstasy"
  - "molly"
  - "fentanyl"
  - "ketamine"
  - "shrooms"
  - "drugdealer"
  - "narcotics"
  - "meth"
  - "klitor"        
  - "vlagalische"   
  - "sperma"        
  - "erekcia"        
  - "minet"          
  - "kunilingus"    
  - "analseks"     
  - "masturbir"      
  - "drochat"       
  - "orgazm"        
  - "trakhat"        
  - "grupovuha"      
  - "porno"        
  - "striptiz"      
  - "blowjob"
  - "handjob"
  - "masturbate"
  - "orgasm"
  - "ejaculate"
  - "cumshot"
  - "gangbang"
  - "pornhub"
  - "onlyfans"
  - "sexting"
  - "nudes"
  - "horny"
  - "intercourse"
  - "genitals"
 
adult-roots:
  - "kokain"
  - "geroin"
  - "gashish"        
  - "zakladk"       
  - "fentanil"
  - "fentanyl"
  - "mdma"
  - "methamphet"
  - "amfetamin"
  - "kristalmeth"   
  - "masturbat"
  - "pornhub"
  - "onlyfans"
  - "blowjob"
  - "handjob"
  - "cumshot"
  - "gangbang"

punishments:
  mute-command: "mute %player% %duration% %reason%"
  ban-command: "ban %player% %duration% %reason%"
  banip-command: "ipban %ip% %duration% %reason%"
  kick-command: "kick %player% %reason%"

  punishments-is-enabled: true

  perm-keywords:
    - "permanent"
    - "perm"
    - "infinity"
    - "inf"
    - "-1"

priority:
  caps: 1
  spam: 2
  insult: 3
  adult-content: 4
  family-insult: 5
  soc-media-dist: 6
  ad-dist: 7

# If true, the plugin will don't apply any warn/censor/blocking etc. to the violators. Plugin will only log every violate. 
# This mode is incompatible with punishments and warns. Consequently, if you enable this mode with another auctions, A.P.V.E's work will aborted.
audit-mode: false

warns:
  warn-limit: 2
  warn-limit-is-enabled: true
  warn-message: |
      &cYour message has been censored due to rule-violating words/meanings in it
      &cPlease, communicate in the chat without any rules-violating words/meanings.
  last-warn-message: |
      &cThis is last warn. Don't write the rule-violating message.
      &cOtherwise, you will be punished by A.P.V.E.

  warn_reset_when_server_restarts: true
  temporary-warns: true
  warn-reset-time: "1h"
  warn_reset_count: 2
  warns-is-enabled: true

insult:
  is-enabled: true
  punishment-is-enabled: true
  duration: "30m"
  reason: "&cYou have been muted due to insulting."
  type: "mute"
  blocking-reason: "&cYour message was blocked because it contains insults."
  blocking: true
  censor-reason: "&cYour message was censored because it contains insults."
  censor: false

family-insult:
  is-enabled: true
  punishment-is-enabled: true
  duration: "8h"
  reason: "&cYou have been muted due to insulting relatives."
  type: "mute"
  blocking-reason: "&cYour message was blocked because it contains family insults."
  blocking: true
  censor-reason: "&cYour message was censored because it contains family insults."
  censor: false

ad-dist:
  is-enabled: true
  punishment-is-enabled: true
  duration: "perm"
  reason: "&cYou have been banned from the server due to distribution of advertisement."
  type: "banip"
  blocking-reason: "&cYour message was blocked because it contains advertisement distribution."
  blocking: true
  censor-reason: "&cYour message was censored because it contains advertisement distribution."
  censor: false

soc-media-dist:
  is-enabled: true
  punishment-is-enabled: true
  duration: "180m"
  reason: "&cYou have been banned from the server due to social media distribution."
  type: "ban"
  blocking-reason: "&cYour message was blocked because it contains social media distribution."
  blocking: true
  censor-reason: "&cYour message was censored because it contains social media distribution."
  censor: false

adult-content:
  is-enabled: true
  punishment-is-enabled: true 
  type: "mute"
  duration: "8h"
  reason: "&cYou have been muted due to 18+ content mention."
  blocking-reason: "&cYour message was blocked because it contains adult (18+) content."
  blocking: true
  censor-reason: "&cYour message was censored because it contains adult (18+) content."
  censor: false
      
spam:
  is-enabled: true
  punishment-is-enabled: true
  max-similar-messages: 3
  time-window-seconds: 60
  similarity-threshold: 0.75
  type: "mute"
  duration: "20m"
  reason: "&cYou have been muted due to spam."
  blocking-reason: "&cYour message was blocked because it is a spam."
  blocking: false

caps:
  is-enabled: true
  punishment-is-enabled: false
  min-message-length: 6
  min-caps-percentage: 70
  type: "mute"
  duration: "15m"
  reason: "&cYou have been muted due to excessive caps."
  blocking-reason: "&cYour message was blocked because it is written in upper case."
  blocking: false
  censor-reason: "&cYour message was censored because it is written in upper case."
  censor: false

intercepted-commands:
  - "msg"
  - "w"
  - "tell"
  - "m"
  - "whisper"
  - "pm"
  - "r"
  - "reply"
  - "nc"
  - "tc"

blocked-domains:
  - "ru"
  - "com"
  - "net"
  - "org"
  - "gg"
  - "io"
  - "xyz"
  - "site"
  - "online"
  - "top"
  - "me"
  - "fun"


command-msg:
  perm-fail: "&cAccess denied."
  help-command-view-req: "&cUnknown commmand. Type /apve help for see available commands. "
  help-command-msg: 
    - "&aAvailable commands:"
    - "&2/apve reload — Reload APVE's configuration"
    - "&2/apve warns show <nickname> — View the player's warns history"
    - "&2/apve warns remove <nickname> <integer> — Remove the player's warns. The removing warns equals <integer> argument."
    - "&2/apve warns clear <nickname> — Remove all the player's warns."

  cfg-reload-msg: "&1Reloading configuration..."
  invalid-syntax: "&cInvalid syntax. Usage: {usage}"
  invalid-number: "&cArgument '{arg}' must be a valid number."
  
  warns:
    no-warns: "&ePlayer {player} currently has no active warns."
    show: "&aPlayer &e{player} &ahas &c{amount} &aactive warns. Highest violation rule: &c{violation}&a."
    removed: "&aSuccessfully removed &e{amount} &awarns from &e{player}&a. Remaining warns: &e{left}&a."
    cleared: "&aAll warns successfully cleared for &e{player}&a."
