name: APVE
version: 1.2.5
main: org.apve.apve
api-version: '1.20.5'
authors: [blackgeyer/blackgeier]
depend:
  - packetevents

commands:
  apve:
    description: APVE management
    usage: /apve <reload|warns>
    permission: apve.use

permissions:
  apve.reload:
    description: Allows reloading APVE config
    default: op

  apve.warns.show:
    description: View the player's warns count
    default: op

  apve.warns.remove:
    description: Allows remove player's warns
    default: op

  apve.warns.clear:
    description: Allows clear player's warns
    default: op

  apve.help:
    description: Allows to use apve help command
    default: op







